### ISSUE TITLE
When Hazelcast member is out of memory, client hangs

### ISSUE THREAD

**Issue by aparnam-asg** [hazelcast/hazelcast-cpp-client#360] opened 2017-12-05 19:04 UTC
I have a situation where I have one single Hazelcast member node. And I want our application to have a failover mode when there is OOM failure in the member. But my client code hangs while trying to open connection or getting a map when member node is down with OOM. Setting timeout in ClientConfig is not helping. Till I kill the member node, it just hangs. What I want is the client calls to throw exception, so our recovery code can do what is needed. 

BTW, this is happening only with native client. For Java client, I get an IllegalStateException within 10 seconds, even without setting any timeout. As this hangs our whole application, will appreciate any help in resolving this as quickly as possible.

Thanks in advance for your time

**Comment by ihsandemir** [comment] 2017-12-06 13:31
Hello @aparnam-asg 

Can you please write this kind of help questions to the user group at https://groups.google.com/forum/#!forum/hazelcast ? 

Having said this, can you please share your client config code? Do you have a reproducer code?

Regards,

**Comment by aparnam-asg** [comment] 2017-12-06 20:16
Thanks @ihsandemir. I will try and use the help forum next time. But this one specifically feels like a bug. 

I have created reproducer code and am attaching the zip file here. It has the java code, native code and output I see when I run those myself. I added a README with steps I did. 

I basically started a member in my IDE by running com.hazelcast.core.server.StartServer with no special configuration. I used my java client to fill the cache in a loop to cause OOM. Java client waits once it can't write anymore and exits when timeout is reached. And if I run again, it quits immediately. But if I run native client, it just hangs there. 

[HazelOOMTest.zip](https://github.com/hazelcast/hazelcast-cpp-client/files/1536714/HazelOOMTest.zip)

**Comment by aparnam-asg** [comment] 2017-12-11 20:22
@ihsandemir is it possible to confirm if you could reproduce this or share your thoughts are on this particular issue? It will help us to plan our strategy . Thanks  for your time

**Comment by ihsandemir** [comment] 2017-12-15 13:33
Hello @aparnam-asg 

I have tried the code piece that you sent for Java. The cpp code file is empty, can you resend it?

Here is some explanation how OOM case is expected to work currently:

When server goes into OOM, then any client request may be served, or unserved depending on the resources at the server side. Also when OOM, our default DefaultOutOfMemoryHandler by default will try shutdown the server, but of course it may fail since you are at OOM case. And if the member is not shutdown, the connection to client is not closed and it may happen that the server may not process the put request but it may respond to the client ping requests. The client put will wait on a server answer, the only way it exits this state is either a a response (it may be a server side exception as well) is received or client heartbeats fail and client closes the connection. 
For example, when I try on my local computer I see that the heartbeat responses are being received with some delay at the client side, hence the client is not closing the connection. Therefore, I observe that the java client is waiting for the future.get() call waiting the response from the server. It does not mean that in every environment it will happen the same way since it is an OOM at the server, there may be several possibilities. In your try, you received the server side exception hence server was lucky to send the exception to the client (com.hazelcast.core.HazelcastException: java.lang.OutOfMemoryError: Java heap space). But at my tries, it could not even communicate this exception to the client because no resources and hence my tries end up in a different scenario.

In this sense, the Java and C++ client acts very similarly, both waits for server response indefinitely from the server until two things happen:
1. Response or exception is received from the server.
2. Client heartbeat timed-out which causes the connection to close and all invocations are set to the correct exception.

In your case, the server may not respond to put request but still may answer to the client ping requests (OOM case is not very deterministic)

Having said this, I believe the best thing to do when server OOM is to detect it prior to it happens and be able to shutdown the server so that the client can close the connection and hence return the expected exception to your application.

Does this make sense to you?

**Comment by aparnam-asg** [comment] 2017-12-15 14:00
Thanks @ihsandemir 
Sorry for the empty file. It is actually nothing much, just creating the client where it hangs. Attaching

[HazelConnectTest.cpp.txt](https://github.com/hazelcast/hazelcast-cpp-client/files/1562926/HazelConnectTest.cpp.txt)

**Comment by ihsandemir** [comment] 2017-12-18 09:39
I ran the code that you sent. The client waits for the owner connection to be established at the authentication response receive. This is currently a blocking connection setup and when the server becomes unresponsive, the client waits there indefinitely. We have plans to change the owner connection setup similar to the Java owner connection setup where it is async. These are the related issues already open for this purpose:

- https://github.com/hazelcast/hazelcast-cpp-client/issues/36
- https://github.com/hazelcast/hazelcast-cpp-client/issues/18

**Comment by ihsandemir** [comment] 2017-12-18 09:43
@aparnam-asg I want to close this issue and lets track this issue by the duplicate issue: https://github.com/hazelcast/hazelcast-cpp-client/issues/18 

Until that issue is solved you may want to detect the server out of memory and shutdown the server before it goes into out-of-memory (e.g. terminate the server when the memory usage is more than 80%)

**Comment by aparnam-asg** [comment] 2017-12-19 16:25
Thanks for checking on this @ihsandemir . Ok, I will watch #18 . 

I was looking at alternate ways to handle this situation and maybe we have something for now. The thing is we don't really want to shutdown but stop putting new entries in IMap when it is about to hit low memory. And we don't want to evict anything. On top of it, when we use memory usage from JVM it doesn't distinguish between actual used and to be GCed. As MemoryMXBean only notifies when it hits threshold and identifying when it is safe to start adding entries again is tricky. When I was testing a solution I came up with, I hit other issues #343  in CPP client that are already filed and had to work around those too. So it kind of morphed into something to work around this.

**Comment by ihsandemir** [comment] 2017-12-19 21:42
@aparnam-asg Why was https://github.com/hazelcast/hazelcast-cpp-client/issues/343 a problem for you? The proxy is automatically created at the server side. The only reason for that issue is that the Java side getDistributedObjects call was not showing the distributed objects in the cluster as expected when we do not send this request but the proxy is actually being created and it works fine. 

You can also stop putting entries, which would also be fine. In this case, the server will respond to the C++ client request and the client will not freeze.

**Comment by aparnam-asg** [comment] 2017-12-19 22:00
@ihsandemir I am trying the following as a strategy though it makes me a bit nervous as it just seems complicated way of doing what we need.

On the Hazelcast server side:
1. Use JVM's MemoryMXBean to get notification and set internal flag when memory hits a certain threshold, say 70%
2. Intercept  put calls for all our maps. If low memory flag is not on, don't do anything, move on
3. If during interception, low memory flag is on, check heap cost of all maps 
4. Allow put call only when this heap cost is reduced by certain percent. Till then fail them

 Basically stop putting new entries till our application has a chance to read what we have put there already without evicting. It will slow the system in that time but we don't hang and continue at a slower pace.

And during 3rd step, I had issues with #343 as maps created by native client are not visible on java side and heap cost was messed up. So I am working around it but putting a hack sort of. Have a "NativeMapCreation" map and intercept a put call to that. Have native client put an entry there with map name when it is creating one. And in the iterceptor on java side, call getMap. So that any calls to getDistributedObject from there on will return this map from native code till our application gets around to reading it.

It is all getting very convoluted at this point. So I don't know if we will even go this route. I didn't want to bother you with all this though. But you asked....:-)

**Comment by ihsandemir** [comment] 2017-12-22 08:24
I am glad that you have a solution. The heap is a problem in general and coding against OOM is not easy at all. Alternatively, did you try using off-heap server version? It does not have OOM problems since it uses off-heap memory.

**Comment by ihsandemir** [comment] 2017-12-22 09:45
Since this issue will be solved by #18 , I am closing this issue.

**Closed by ihsandemir** 2017-12-22 09:45 UTC
Labels: question, Type: Defect

**Comment by aparnam-asg** [comment] 2017-12-22 13:57
Thanks @ihsandemir
By off-heap server, you must mean to use the high density, native objects. As it is enterprise only as per documentation, we are looking for universal solution which doesn't require special licensing for the feature.

**Comment by ihsandemir** [comment] 2017-12-22 14:56
yes, that is enterprise-feature.
