### ISSUE TITLE
Test write_null_portable on PortableWriter [API-1252]

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-cpp-client#960] opened 2022-03-02 10:00 UTC
Cpp code has following exceptions in ClassDefinitionWriter

```
  BOOST_THROW_EXCEPTION(exception::hazelcast_serialization(
              "ClassDefWriter::write_null_portable",
              "Cannot write null portable without explicitly registering class "
              "definition!"));
``` 

In theory, it should not be needed in c++ (unlike java), since in c++ class definition can be created from the template. 
We need to add tests for `write_null_portable` and delete unneeded codes .

**Comment by hakanaktas0** [comment] 2022-08-23 12:21
C++ client doesn't create class definition automatically when write_null_portable is called. After testing some possible scenarios I can say that C++ client behaves pretty much identical to Java client. Before calling write_null_portable, something not null must be written or class definition should be registered explicitly, otherwise exception in question is thrown.

**Comment by ihsandemir** [comment] 2022-08-23 13:47
@hakanaktas0 Since this is expected behaviour, we can say that we will not fix anything and close the issue.

**Closed** 2022-08-23 14:00 UTC
Labels: Type: Defect, Source: Internal, to-jira
