### ISSUE TITLE
FieldTypes skips boolean array

### ISSUE THREAD

**Issue by roycepipkins** [hazelcast/hazelcast-cpp-client#236] opened 2017-03-06 22:25 UTC
It looks to me like FieldTypes in FieldType.h misses the boolean array type. Type 12. So starting with Char array every subsequent field type has a value that is too low by one. This was against server 3.6.6.

**Comment by ihsandemir** [comment] 2017-03-07 14:50
Hello,

yes, indeed there is an issue already opened for this: https://github.com/hazelcast/hazelcast-cpp-client/issues/230  It will be fixed in the upcoming release. Thanks for reporting.

**Comment by ihsandemir** [comment] 2017-03-15 14:10
Duplicate of #230

**Closed by ihsandemir** 2017-03-15 14:10 UTC
Labels: duplicate
