### ISSUE TITLE
ClientPNCounterConsistencyLostTest.driverCanContinueSessionByCallingReset Test Failure [API-1944]

### ISSUE THREAD

**Issue by akeles85** [hazelcast/hazelcast-cpp-client#1148] opened 2023-03-07 14:36 UTC
C++ compiler version: gcc 11.3
Hazelcast Cpp client version: 5.1.0
Hazelcast server version: 5.2.0
Number of the clients: 1
Cluster size, i.e. the number of Hazelcast cluster members: 1
OS version (Windows/Linux/OSX): Ubuntu x64

Please attach relevant logs and files for client and server side.

#### Expected behaviour
Test pass successfully

#### Actual behaviour
[  FAILED  ] ClientPNCounterConsistencyLostTest.driverCanContinueSessionByCallingReset

#### Steps to reproduce the behaviour.
The error occurs randomly at Github actions.

Here is the link. [https://github.com/hazelcast/hazelcast-cpp-client/actions/runs/4326857481/jobs/7554794286](url)
[error_logs.txt](https://github.com/hazelcast/hazelcast-cpp-client/files/10910470/error_logs.txt)

**Comment by OzanCansel** [comment] 2023-03-14 14:20
Duplicate of #1153

**Closed by OzanCansel** 2023-03-14 14:20 UTC
Labels: Type: Test-Failure, to-jira
