### ISSUE TITLE
cmake build error for Library

### ISSUE THREAD

**Issue by andysCaplin** [hazelcast/hazelcast-cpp-client#876] opened 2021-05-12 08:29 UTC
C++ compiler version: g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
OS version (Windows/Linux/OSX): Linux Centos 7

#### Expected behaviour
Expected version 4.1 to build on Linux. Version 4.0 built ok on same machine

#### Actual behaviour
Building version 4.1 of the library works for us on Windows and OSx but fails on Linux.

We get the errors shown below. Note: re the initial cmake warnings

- We got the same warnings on the previous successful build of 4.0
- They seem to be red herrings as they refer to the line below but further on in the log it clearly states that the build has found the boost libraries - thread, chrone, date_time and atomic
```
find_package(Boost 1.71 REQUIRED COMPONENTS thread chrono)
```

```
-- The CXX compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- GIT_COMMIT_DATE = Thu May 6 14:32:43 2021 +0300
-- GIT_COMMIT_ID = 361fd76d
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Warning at /usr/local/cmake-3.14.1/share/cmake-3.14/Modules/FindBoost.cmake:896 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/cmake-3.14.1/share/cmake-3.14/Modules/FindBoost.cmake:1018 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/cmake-3.14.1/share/cmake-3.14/Modules/FindBoost.cmake:1694 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:82 (find_package)


CMake Warning at /usr/local/cmake-3.14.1/share/cmake-3.14/Modules/FindBoost.cmake:896 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/cmake-3.14.1/share/cmake-3.14/Modules/FindBoost.cmake:1018 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/cmake-3.14.1/share/cmake-3.14/Modules/FindBoost.cmake:1694 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:82 (find_package)


CMake Warning at /usr/local/cmake-3.14.1/share/cmake-3.14/Modules/FindBoost.cmake:896 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/cmake-3.14.1/share/cmake-3.14/Modules/FindBoost.cmake:1018 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/cmake-3.14.1/share/cmake-3.14/Modules/FindBoost.cmake:1694 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:82 (find_package)


CMake Warning at /usr/local/cmake-3.14.1/share/cmake-3.14/Modules/FindBoost.cmake:896 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/cmake-3.14.1/share/cmake-3.14/Modules/FindBoost.cmake:1018 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/cmake-3.14.1/share/cmake-3.14/Modules/FindBoost.cmake:1694 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:82 (find_package)


-- Boost version: 1.71.0
-- Found the following Boost libraries:
--   thread
--   chrono
--   date_time
--   atomic
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuration summary:
--   CMAKE_BUILD_TYPE =      Release
--   BUILD_SHARED_LIBS =     OFF
--   WITH_OPENSSL =          OFF
--   DISABLE_LOGGING =       OFF
--   CMAKE_INSTALL_PREFIX =  /usr/local
--   BUILD_TESTS =           OFF
--   BUILD_EXAMPLES =        OFF
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_SHARED_LIB
    BUILD_STATIC_LIB


-- Build files have been written to: /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/build
2021/05/11-22:51:46: [INFO] Cmake create build files passed
Scanning dependencies of target hazelcast-cpp-client
[  5%] Building CXX object CMakeFiles/hazelcast-cpp-client.dir/hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.cpp.o
[ 10%] Building CXX object CMakeFiles/hazelcast-cpp-client.dir/hazelcast/src/hazelcast/client/client_impl.cpp.o
[ 15%] Building CXX object CMakeFiles/hazelcast-cpp-client.dir/hazelcast/src/hazelcast/client/cluster.cpp.o
[ 21%] Building CXX object CMakeFiles/hazelcast-cpp-client.dir/hazelcast/src/hazelcast/client/config.cpp.o
In file included from /usr/include/c++/4.8.2/bits/hashtable.h:35:0,
                 from /usr/include/c++/4.8.2/unordered_set:47,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/include/hazelcast/client/client_config.h:19,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/src/hazelcast/client/config.cpp:34:
/usr/include/c++/4.8.2/bits/hashtable_policy.h: In instantiation of ‘std::__detail::_Hash_node<_Value, true>::_Hash_node(_Args&& ...) [with _Args = {const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Value = std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config>]’:
/usr/include/c++/4.8.2/ext/new_allocator.h:120:4:   required from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::__detail::_Hash_node<std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config>, true>; _Args = {const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Tp = std::__detail::_Hash_node<std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config>, true>]’
/usr/include/c++/4.8.2/bits/hashtable.h:727:6:   required from ‘std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__node_type* std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_M_allocate_node(_Args&& ...) [with _Args = {const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Key = std::basic_string<char>; _Value = std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config>; _Alloc = std::allocator<std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config> >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<std::basic_string<char> >; _H1 = std::hash<std::basic_string<char> >; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__node_type = std::__detail::_Hash_node<std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config>, true>]’
/usr/include/c++/4.8.2/bits/hashtable.h:1260:71:   required from ‘std::pair<typename std::__detail::_Hashtable_base<_Key, _Value, _ExtractKey, _Equal, _H1, _H2, _Hash, _Traits>::iterator, bool> std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_M_emplace(std::true_type, _Args&& ...) [with _Args = {const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Key = std::basic_string<char>; _Value = std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config>; _Alloc = std::allocator<std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config> >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<std::basic_string<char> >; _H1 = std::hash<std::basic_string<char> >; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>; typename std::__detail::_Hashtable_base<_Key, _Value, _ExtractKey, _Equal, _H1, _H2, _Hash, _Traits>::iterator = std::__detail::_Node_iterator<std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config>, false, true>; std::true_type = std::integral_constant<bool, true>]’
/usr/include/c++/4.8.2/bits/hashtable.h:665:69:   required from ‘std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__ireturn_type std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::emplace(_Args&& ...) [with _Args = {const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Key = std::basic_string<char>; _Value = std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config>; _Alloc = std::allocator<std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config> >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<std::basic_string<char> >; _H1 = std::hash<std::basic_string<char> >; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__ireturn_type = std::pair<std::__detail::_Node_iterator<std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config>, false, true>, bool>]’
/usr/include/c++/4.8.2/bits/unordered_map.h:311:54:   required from ‘std::pair<typename std::_Hashtable<_Key, std::pair<const _Key, _Tp>, _Alloc, std::__detail::_Select1st, _Pred, _Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<std::__not_<std::__and_<std::__is_fast_hash<_Hash>, std::is_default_constructible<_Hash>, std::is_copy_assignable<_Hash>, std::__detail::__is_noexcept_hash<_Key, _Hash> > >::value, false, true> >::iterator, bool> std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::emplace(_Args&& ...) [with _Args = {const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Key = std::basic_string<char>; _Tp = hazelcast::client::config::reliable_topic_config; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config> >; typename std::_Hashtable<_Key, std::pair<const _Key, _Tp>, _Alloc, std::__detail::_Select1st, _Pred, _Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<std::__not_<std::__and_<std::__is_fast_hash<_Hash>, std::is_default_constructible<_Hash>, std::is_copy_assignable<_Hash>, std::__detail::__is_noexcept_hash<_Key, _Hash> > >::value, false, true> >::iterator = std::__detail::_Node_iterator<std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config>, false, true>]’
/home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/src/hazelcast/client/config.cpp:859:65:   required from here
/usr/include/c++/4.8.2/bits/hashtable_policy.h:177:55: error: no matching function for call to ‘std::pair<const std::basic_string<char>, hazelcast::client::config::reliable_topic_config>::pair(const std::basic_string<char>&, const std::basic_string<char>&)’
  : _M_v(std::forward<_Args>(__args)...), _M_hash_code() { }
                                                       ^
/usr/include/c++/4.8.2/bits/hashtable_policy.h:177:55: note: candidates are:
In file included from /usr/include/c++/4.8.2/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/4.8.2/vector:60,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/include/hazelcast/client/client_config.h:18,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/src/hazelcast/client/config.cpp:34:
/usr/include/c++/4.8.2/bits/stl_pair.h:206:9: note: template<class ... _Args1, long unsigned int ..._Indexes1, class ... _Args2, long unsigned int ..._Indexes2> std::pair<_T1, _T2>::pair(std::tuple<_Args1 ...>&, std::tuple<_Args2 ...>&, std::_Index_tuple<_Indexes1 ...>, std::_Index_tuple<_Indexes2 ...>)
         pair(tuple<_Args1...>&, tuple<_Args2...>&,
         ^
/usr/include/c++/4.8.2/bits/stl_pair.h:206:9: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/4.8.2/bits/hashtable.h:35:0,
                 from /usr/include/c++/4.8.2/unordered_set:47,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/include/hazelcast/client/client_config.h:19,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/src/hazelcast/client/config.cpp:34:
/usr/include/c++/4.8.2/bits/hashtable_policy.h:177:55: note:   types ‘std::tuple<_Elements ...>’ and ‘const std::basic_string<char>’ have incompatible cv-qualifiers
  : _M_v(std::forward<_Args>(__args)...), _M_hash_code() { }
                                                       ^
In file included from /usr/include/c++/4.8.2/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/4.8.2/vector:60,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/include/hazelcast/client/client_config.h:18,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/src/hazelcast/client/config.cpp:34:
/usr/include/c++/4.8.2/bits/stl_pair.h:155:9: note: template<class ... _Args1, class ... _Args2> std::pair<_T1, _T2>::pair(std::piecewise_construct_t, std::tuple<_Args1 ...>, std::tuple<_Args2 ...>)
         pair(piecewise_construct_t, tuple<_Args1...>, tuple<_Args2...>);
         ^
/usr/include/c++/4.8.2/bits/stl_pair.h:155:9: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/4.8.2/bits/hashtable.h:35:0,
                 from /usr/include/c++/4.8.2/unordered_set:47,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/include/hazelcast/client/client_config.h:19,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/src/hazelcast/client/config.cpp:34:
/usr/include/c++/4.8.2/bits/hashtable_policy.h:177:55: note:   cannot convert ‘std::forward<const std::basic_string<char>&>((* & __args#0))’ (type ‘const std::basic_string<char>’) to type ‘std::piecewise_construct_t’
  : _M_v(std::forward<_Args>(__args)...), _M_hash_code() { }
                                                       ^
In file included from /usr/include/c++/4.8.2/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/4.8.2/vector:60,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/include/hazelcast/client/client_config.h:18,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/src/hazelcast/client/config.cpp:34:
/usr/include/c++/4.8.2/bits/stl_pair.h:150:12: note: template<class _U1, class _U2, class> constexpr std::pair<_T1, _T2>::pair(std::pair<_U1, _U2>&&)
  constexpr pair(pair<_U1, _U2>&& __p)
            ^
/usr/include/c++/4.8.2/bits/stl_pair.h:150:12: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/4.8.2/bits/hashtable.h:35:0,
                 from /usr/include/c++/4.8.2/unordered_set:47,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/include/hazelcast/client/client_config.h:19,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/src/hazelcast/client/config.cpp:34:
/usr/include/c++/4.8.2/bits/hashtable_policy.h:177:55: note:   types ‘std::pair<_T1, _T2>’ and ‘const std::basic_string<char>’ have incompatible cv-qualifiers
  : _M_v(std::forward<_Args>(__args)...), _M_hash_code() { }
                                                       ^
In file included from /usr/include/c++/4.8.2/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/4.8.2/vector:60,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/include/hazelcast/client/client_config.h:18,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/src/hazelcast/client/config.cpp:34:
/usr/include/c++/4.8.2/bits/stl_pair.h:144:12: note: template<class _U1, class _U2, class> constexpr std::pair<_T1, _T2>::pair(_U1&&, _U2&&)
  constexpr pair(_U1&& __x, _U2&& __y)
            ^
/usr/include/c++/4.8.2/bits/stl_pair.h:144:12: note:   template argument deduction/substitution failed:
/usr/include/c++/4.8.2/bits/stl_pair.h:141:38: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
       template<class _U1, class _U2, class = typename
                                      ^
/usr/include/c++/4.8.2/bits/stl_pair.h:138:12: note: template<class _U2, class> constexpr std::pair<_T1, _T2>::pair(const _T1&, _U2&&)
  constexpr pair(const _T1& __x, _U2&& __y)
            ^
/usr/include/c++/4.8.2/bits/stl_pair.h:138:12: note:   template argument deduction/substitution failed:
/usr/include/c++/4.8.2/bits/stl_pair.h:136:27: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
       template<class _U2, class = typename
                           ^
/usr/include/c++/4.8.2/bits/stl_pair.h:133:12: note: template<class _U1, class> constexpr std::pair<_T1, _T2>::pair(_U1&&, const _T2&)
  constexpr pair(_U1&& __x, const _T2& __y)
            ^
/usr/include/c++/4.8.2/bits/stl_pair.h:133:12: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/4.8.2/bits/hashtable.h:35:0,
                 from /usr/include/c++/4.8.2/unordered_set:47,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/include/hazelcast/client/client_config.h:19,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/src/hazelcast/client/config.cpp:34:
/usr/include/c++/4.8.2/bits/hashtable_policy.h:177:55: note:   cannot convert ‘std::forward<const std::basic_string<char>&>((* & __args#1))’ (type ‘const std::basic_string<char>’) to type ‘const hazelcast::client::config::reliable_topic_config&’
  : _M_v(std::forward<_Args>(__args)...), _M_hash_code() { }
                                                       ^
In file included from /usr/include/c++/4.8.2/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/4.8.2/vector:60,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/include/hazelcast/client/client_config.h:18,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/src/hazelcast/client/config.cpp:34:
/usr/include/c++/4.8.2/bits/stl_pair.h:128:17: note: constexpr std::pair<_T1, _T2>::pair(std::pair<_T1, _T2>&&) [with _T1 = const std::basic_string<char>; _T2 = hazelcast::client::config::reliable_topic_config]
       constexpr pair(pair&&) = default;
                 ^
/usr/include/c++/4.8.2/bits/stl_pair.h:128:17: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/4.8.2/bits/stl_pair.h:127:17: note: constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const std::basic_string<char>; _T2 = hazelcast::client::config::reliable_topic_config]
       constexpr pair(const pair&) = default;
                 ^
/usr/include/c++/4.8.2/bits/stl_pair.h:127:17: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/4.8.2/bits/stl_pair.h:124:12: note: template<class _U1, class _U2, class> constexpr std::pair<_T1, _T2>::pair(const std::pair<_U1, _U2>&)
  constexpr pair(const pair<_U1, _U2>& __p)
            ^
/usr/include/c++/4.8.2/bits/stl_pair.h:124:12: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/4.8.2/bits/hashtable.h:35:0,
                 from /usr/include/c++/4.8.2/unordered_set:47,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/include/hazelcast/client/client_config.h:19,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/src/hazelcast/client/config.cpp:34:
/usr/include/c++/4.8.2/bits/hashtable_policy.h:177:55: note:   ‘const std::basic_string<char>’ is not derived from ‘const std::pair<_T1, _T2>’
  : _M_v(std::forward<_Args>(__args)...), _M_hash_code() { }
                                                       ^
In file included from /usr/include/c++/4.8.2/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/4.8.2/vector:60,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/include/hazelcast/client/client_config.h:18,
                 from /home/build/workspace/Hazelcast-Poller-Build-EL7/hazelcast-cpp-client/hazelcast/src/hazelcast/client/config.cpp:34:
/usr/include/c++/4.8.2/bits/stl_pair.h:112:26: note: constexpr std::pair<_T1, _T2>::pair(const _T1&, const _T2&) [with _T1 = const std::basic_string<char>; _T2 = hazelcast::client::config::reliable_topic_config]
       _GLIBCXX_CONSTEXPR pair(const _T1& __a, const _T2& __b)
                          ^
/usr/include/c++/4.8.2/bits/stl_pair.h:112:26: note:   no known conversion for argument 2 from ‘const std::basic_string<char>’ to ‘const hazelcast::client::config::reliable_topic_config&’
/usr/include/c++/4.8.2/bits/stl_pair.h:108:26: note: constexpr std::pair<_T1, _T2>::pair() [with _T1 = const std::basic_string<char>; _T2 = hazelcast::client::config::reliable_topic_config]
       _GLIBCXX_CONSTEXPR pair()
                          ^
/usr/include/c++/4.8.2/bits/stl_pair.h:108:26: note:   candidate expects 0 arguments, 2 provided
gmake[2]: *** [CMakeFiles/hazelcast-cpp-client.dir/hazelcast/src/hazelcast/client/config.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/hazelcast-cpp-client.dir/all] Error 2
gmake: *** [all] Error 2
```

**Comment by ihsandemir** [comment] 2021-05-12 09:39
hello @andysCaplin Does [this PR](https://github.com/hazelcast/hazelcast-cpp-client/pull/872) branch solve this problem for you?

**Comment by andysCaplin** [comment] 2021-05-12 13:39
The PR branch fixes the build. Cheers.

Any idea why we're getting the cmake warnings ? They don't cause and issue but I'm just curious.

**Comment by ihsandemir** [comment] 2021-05-12 15:52
If you are asking the warning `New Boost version may have incorrect or missing dependencies and imported targets`, it is because you cmake version may be older version, but this is not really important. See  https://stackoverflow.com/questions/42123509/cmake-finds-boost-but-the-imported-targets-not-available-for-boost-version and https://stackoverflow.com/questions/57415206/is-there-a-way-to-get-rid-of-the-new-boost-version-may-have-incorrect-or-missin

By the way, the fix PR is merged into the master already and we will probably make a patch release 4.1.1 for this fix.

**Comment by ihsandemir** [comment] 2021-05-17 07:53
@andysCaplin Can we close the issue if the problem is solved?

**Comment by andysCaplin** [comment] 2021-05-17 10:48
Yes - definitely. Cheers. What's the timescale for the 4.11 release ?

**Comment by yemreinci** [comment] 2021-05-21 09:54
Hello @andysCaplin, we have planned the 4.1.1 release for next week. 

I'm closing this issue as it was solved. Feel free to open more issues for problems that you may experience in the future.

Thanks.

**Closed by yemreinci** 2021-05-21 09:54 UTC
Labels: Source: Community, Type: Defect, to-jira

**Comment by andysCaplin** [comment] 2021-05-27 09:22
Just got the 4.1.1 official release and it fixes the issue.
