### ISSUE TITLE
strange in_predicate behaviour

### ISSUE THREAD

**Issue by wsw2016** [hazelcast/hazelcast-cpp-client#888] opened 2021-06-15 19:04 UTC
C++ compiler version: gcc-9
Hazelcast Cpp client version: 4.1.1
Hazelcast server version: 4.2
Number of the clients: 1
Cluster size, i.e. the number of Hazelcast cluster members: 1
OS version (Windows/Linux/OSX): Linux

Please attach relevant logs and files for client and server side.

#### Expected behaviour
Having a map<string, string> I would expect the in_predicate for keys to contain a vector<string> similar to queryExample.cpp
e.g.
```
std::vector<std::string> myKeys ...;
map->remove_all(query::in_predicate(hz, query::query_constants::KEY_ATTRIBUTE_NAME, myKeys)).get();
```

#### Actual behaviour
```
It works for one string:
map->remove_all(query::in_predicate(hz, query::query_constants::KEY_ATTRIBUTE_NAME, myKeys[0])).get();
but it does not work for a vector<string>:
map->remove_all(query::in_predicate(hz, query::query_constants::KEY_ATTRIBUTE_NAME, myKeys)).get();

```

The main use-case for me is a fast removal of thousands of entries - without predicates I would have to start a lot of futures in imap->delete_entry with presumable a lot of overhead. If this is expected behaviour, it should be annoted at least in the source code, e.g. in predicates.h.

#### Steps to reproduce the behaviour
```
int main()
{
    auto hz = hazelcast::new_client().get();
    auto map = hz.get_map("testmap").get();
    map->clear().get();
    std::vector<uint8_t> test1(5, 112);
    map->put<std::string, std::string >("12", "hello").get();
    map->put<std::string, std::string >("23", "world").get();
    map->put<std::string, std::string >("34", "!!!!").get();


    std::vector<std::string> myKeys;
    myKeys.push_back("12");
    myKeys.push_back("34");

    auto v = map->entry_set<std::string, std::string>(
                query::in_predicate(hz, query::query_constants::KEY_ATTRIBUTE_NAME, myKeys)).get();

    assert(v.size() == 2);

    map->remove_all(query::in_predicate(hz, query::query_constants::KEY_ATTRIBUTE_NAME, myKeys)).get();

    return 0;
}
```

**Comment by ihsandemir** [comment] 2021-06-16 16:15
Hello @wsw2016  The current API was designed to pass the removal items in the parameter list, but surely another constructor API accepting a vector of items can also be added.

**Comment by wsw2016** [comment] 2021-06-16 17:30
I think the API is ok, it works on C++ side perfectly. If we look in the example queryExample.cpp you will find exactly the same situation:

```
    std::vector<int> inVals{4, 10, 19};
    values = intMap->values<int, query::in_predicate>(
            query::in_predicate(client, query::query_constants::KEY_ATTRIBUTE_NAME, inVals)).get();

```
The problem is on the Java-side or in the protocol between. If I insert strings instead of int in this example (see my example above) I get following exception from the Java-Server. The error String is not castable to Comparable is strange - probably somebody should look on the Java-implementation of in_predicate.

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<hazelcast::client::exception::hazelcast_serialization> >'
  what():  hazelcast_serialization {Problem while reading DataSerializable, namespace: -20, ID: 7, class: 'null', exception: class [Ljava.lang.String; cannot be cast to class java.lang.Comparable ([Ljava.lang.String; and java.lang.Comparable are in module java.base of loader 'bootstrap'). Error code:21, Details:Error code:21, Class name that generated the error:com.hazelcast.nio.serialization.HazelcastSerializationException, Problem while reading DataSerializable, namespace: -20, ID: 7, class: 'null', exception: class [Ljava.lang.String; cannot be cast to class java.lang.Comparable ([Ljava.lang.String; and java.lang.Comparable are in module java.base of loader 'bootstrap')
         DataSerializableSerializer.java line 183 :com.hazelcast.internal.serialization.impl.DataSerializableSerializer.rethrowReadException
         DataSerializableSerializer.java line 164 :com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal
         DataSerializableSerializer.java line 106 :com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read
         DataSerializableSerializer.java line 51 :com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read
         StreamSerializerAdapter.java line 44 :com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read
         AbstractSerializationService.java line 208 :com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject
         MapEntriesWithPredicateMessageTask.java line 47 :com.hazelcast.client.impl.protocol.task.map.MapEntriesWithPredicateMessageTask.getPredicate
         AbstractMapQueryMessageTask.java line 91 :com.hazelcast.client.impl.protocol.task.map.AbstractMapQueryMessageTask.call
         AbstractCallableMessageTask.java line 35 :com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage
         AbstractMessageTask.java line 153 :com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage
         AbstractMessageTask.java line 116 :com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run
         ThreadPoolExecutor.java line 1130 :java.util.concurrent.ThreadPoolExecutor.runWorker
         ThreadPoolExecutor.java line 630 :java.util.concurrent.ThreadPoolExecutor$Worker.run
         Thread.java line 832 :java.lang.Thread.run
         HazelcastManagedThread.java line 76 :com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun
         HazelcastManagedThread.java line 102 :com.hazelcast.internal.util.executor.HazelcastManagedThread.run
.} at com.hazelcast.nio.serialization.HazelcastSerializationException.

```

**Comment by ihsandemir** [comment] 2021-06-21 09:46
Hello @wsw2016 I debugged the problem. As I previously indicated, the API needs a list of items those are to be sent to the server side and each of those items needs to be Comparable at the server side. In your case, if you use a vector, due to the template deduction it assumes that there is only one item provided and it is of type vector. Then this predicate data becomes `String[2]={"12", "34"}` at the server side and this is not implementing the `Comparable` interface as the server needs in order to compare and decide if an item is to be returned or not. Hence, the problem is that the API is designed to receive each item one by one in a parameter sequence. We need to add a template specialization fi it is a vector to handle it properly and pass each item in the vector to the server side as expected.

For example, the following code works, but I believe that you need to use a vector for your case since you have so many items. Hence, I believe we need to add that to the `in_predicate` API.

```
                auto hz = hazelcast::new_client().get();
                auto map = hz.get_map("testmap").get();
                map->clear().get();
                std::vector<uint8_t> test1(5, 112);
                map->put<std::string, std::string >("12", "hello").get();
                map->put<std::string, std::string >("23", "world").get();
                map->put<std::string, std::string >("34", "!!!!").get();

                std::vector<std::string> myKeys;
                myKeys.push_back("12");
                myKeys.push_back("34");

                auto v = map->entry_set<std::string, std::string>(
                        query::in_predicate(hz, query::query_constants::KEY_ATTRIBUTE_NAME, "12", "34")).get();

                assert(v.size() == 2);

                map->remove_all(query::in_predicate(hz, query::query_constants::KEY_ATTRIBUTE_NAME, "12", "34")).get();
```

**Comment by wsw2016** [comment] 2021-06-21 10:53
Probably you are right. My problem is, that it works in the example:
 ```
// in_predicate
// key in {4, 10, 19}
std::vector<int> inVals{4, 10, 19};
values = intMap->values<int, query::in_predicate>(
            query::in_predicate(client, query::query_constants::KEY_ATTRIBUTE_NAME, inVals)).get();
```
To have a clear API we need something like a `vector<KeyType>` to be useable in in_predicate. From API point of view it is strange, that it works for `int,` but not for `string`. I think you are free to claim, that the third attribute is always a std::vector, with the type is defined per template.

As a backup an example could be provided, how to encode the request manually, so that "high-performance" fraction could use C-strings and arrays. I think something like that was there in version 3. A good place is queryExample.cpp.

**Comment by yemreinci** [comment] 2021-06-21 16:54
> Probably you are right. My problem is, that it works in the example:

@wsw2016 I am afraid the snippet in queryExample.cpp that you are referring to also doesn't work:

```c++
#include <hazelcast/client/hazelcast_client.h>
#include <hazelcast/client/query/predicates.h>

namespace query = hazelcast::client::query;

int main() {
    auto client = hazelcast::new_client().get();

    auto intMap = client.get_map("map").get();

    const int numItems = 20;
    for (int i = 0; i < numItems; ++i) {
        intMap->put(i, 2 * i);
    }

    std::vector<int> inVals{4, 10, 19};
    auto values = intMap->values<int, query::in_predicate>(
            query::in_predicate(client, query::query_constants::KEY_ATTRIBUTE_NAME, inVals)).get();

    for (auto x: values) {
        std::cout << x << ' ';
    }
    std::cout << '\n';
    return 0;
}
```
outputs:
```
terminate called after throwing an instance of 'boost::wrapexcept<hazelcast::client::exception::hazelcast_serialization>'
  what():  hazelcast_serialization {Problem while reading DataSerializable, namespace: -20, ID: 7, class: 'null', exception: class [I cannot be cast to class java.lang.Comparable ([I and java.lang.Comparable are in module java.base of loader 'bootstrap'). Error code:21, Details:Error code:21, Class name that generated the error:com.hazelcast.nio.serialization.HazelcastSerializationException, Problem while reading DataSerializable, namespace: -20, ID: 7, class: 'null', exception: class [I cannot be cast to class java.lang.Comparable ([I and java.lang.Comparable are in module java.base of loader 'bootstrap')
	 DataSerializableSerializer.java line 183 :com.hazelcast.internal.serialization.impl.DataSerializableSerializer.rethrowReadException
	 DataSerializableSerializer.java line 164 :com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal
	 DataSerializableSerializer.java line 106 :com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read
	 DataSerializableSerializer.java line 51 :com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read
	 StreamSerializerAdapter.java line 44 :com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read
	 AbstractSerializationService.java line 208 :com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject
	 MapValuesWithPredicateMessageTask.java line 54 :com.hazelcast.client.impl.protocol.task.map.MapValuesWithPredicateMessageTask.getPredicate
	 AbstractMapQueryMessageTask.java line 91 :com.hazelcast.client.impl.protocol.task.map.AbstractMapQueryMessageTask.call
	 AbstractCallableMessageTask.java line 35 :com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage
	 AbstractMessageTask.java line 153 :com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage
	 AbstractMessageTask.java line 116 :com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run
	 ThreadPoolExecutor.java line 1128 :java.util.concurrent.ThreadPoolExecutor.runWorker
	 ThreadPoolExecutor.java line 628 :java.util.concurrent.ThreadPoolExecutor$Worker.run
	 Thread.java line 829 :java.lang.Thread.run
	 HazelcastManagedThread.java line 76 :com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun
	 HazelcastManagedThread.java line 102 :com.hazelcast.internal.util.executor.HazelcastManagedThread.run
.} at com.hazelcast.nio.serialization.HazelcastSerializationException.
```

I don't know whether this snippet worked in any of the older versions, but the currently, it's not possible to delete a dynamic list of keys by using the "IN" query predicate - you need to pass every item statically as a parameter.  As @ihsandemir stated, passing a vector will be interpreted as deleting a key with the type vector and it will cause errors on the server.

**Comment by ihsandemir** [comment] 2021-06-21 21:23
@wsw2016 You are correct, it was accepting vector of entries in [3.x version](https://github.com/hazelcast/hazelcast-cpp-client/blob/v3.12.1/hazelcast/include/hazelcast/client/query/InPredicate.h#L45). We need to add that to the API for sure. And yes, the example compiles but it produces the same error. We need to fix it. Thanks for reporting it.

**Comment by ihsandemir** [comment] 2021-06-21 21:55
I submitted a [fix PR](https://github.com/hazelcast/hazelcast-cpp-client/pull/890), please review.

**Closed** 2021-06-30 14:08 UTC
Labels: Source: Community, Type: Defect, to-jira

**Comment by ihsandemir** [comment] 2021-06-30 14:09
@wsw2016 I merged the new API, can you please try from the master branch and let me know how it works for you?

**Comment by wsw2016** [comment] 2021-07-02 13:08
It works (partially). I had an issue with compiling into my C++-17 - dynamic library of your C++11-compiled-static client. With earlier versions it worked off-the-shelf. Now I had to change manually the CMakeLists to 17 in root directory. After that it worked properly. I opened a new issue with this 11-17 incompatibility.
 

Gesendet: Mittwoch, 30. Juni 2021 um 16:09 Uhr
Von: "ihsan demir" ***@***.***>
An: "hazelcast/hazelcast-cpp-client" ***@***.***>
Cc: "wsw2016" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [hazelcast/hazelcast-cpp-client] strange in_predicate behaviour (#888)


 

@wsw2016 I merged the new API, can you please try from the master branch and let me know how it works for you?
