### ISSUE TITLE
"cmake --build ." fail: error: ambiguous template

### ISSUE THREAD

**Issue by whoareu** [hazelcast/hazelcast-cpp-client#859] opened 2021-04-28 09:30 UTC
C++ compiler version: cmake version 3.19.8
Hazelcast Cpp client version: hazelcast-cpp-client-4.0.1
Hazelcast server version: no
Number of the clients: no
Cluster size, i.e. the number of Hazelcast cluster members: no
OS version (Windows/Linux/OSX):
Linux
Please attach relevant logs and files for client and server side.
client: 
```
!362 # cmake --build  . --target install
[  5%] Building CXX object CMakeFiles/hazelcast-cpp-client.dir/hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.cpp.o
In file included from /tmp/hazelcast-cpp-client-4.0.1/hazelcast/include/hazelcast/client/address.h:20:0,
                 from /tmp/hazelcast-cpp-client-4.0.1/hazelcast/include/hazelcast/client/member.h:22,
                 from /tmp/hazelcast-cpp-client-4.0.1/hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.cpp:18:
/tmp/hazelcast-cpp-client-4.0.1/hazelcast/include/hazelcast/client/serialization/serialization.h:93:17: warning: type attributes ignored after type is already defined [-Wattributes]
                 };
                 ^
In file included from /tmp/hazelcast-cpp-client-4.0.1/hazelcast/include/hazelcast/client/address.h:20:0,
                 from /tmp/hazelcast-cpp-client-4.0.1/hazelcast/include/hazelcast/client/member.h:22,
                 from /tmp/hazelcast-cpp-client-4.0.1/hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.cpp:18:
/tmp/hazelcast-cpp-client-4.0.1/hazelcast/include/hazelcast/client/serialization/serialization.h:776:32: error: ambiguous template specialization ‘write_object<>’ for ‘void hazelcast::client::serialization::object_data_output::write_object(const char*)’
             void HAZELCAST_API object_data_output::write_object(const char *object);
                                ^
/tmp/hazelcast-cpp-client-4.0.1/hazelcast/include/hazelcast/client/serialization/serialization.h:719:22: note: candidates are: template<class T> void hazelcast::client::serialization::object_data_output::write_object(const T*)
                 void write_object(const T *object);
                      ^
/tmp/hazelcast-cpp-client-4.0.1/hazelcast/include/hazelcast/client/serialization/serialization.h:753:24: note:                 template<class T> typename std::enable_if<(!((((std::is_base_of<hazelcast::client::serialization::builtin_serializer, hazelcast::client::serialization::hz_serializer<T> >::value || std::is_base_of<hazelcast::client::serialization::identified_data_serializer, hazelcast::client::serialization::hz_serializer<T> >::value) || std::is_base_of<hazelcast::client::serialization::portable_serializer, hazelcast::client::serialization::hz_serializer<T> >::value) || std::is_base_of<hazelcast::client::serialization::custom_serializer, hazelcast::client::serialization::hz_serializer<T> >::value) || (std::is_array< <template-parameter-1-1> >::value && std::is_same<typename std::remove_all_extents< <template-parameter-1-1> >::type, char>::value))), void>::type hazelcast::client::serialization::object_data_output::write_object(T)
                 inline write_object(const T object);
                        ^
In file included from /tmp/hazelcast-cpp-client-4.0.1/hazelcast/include/hazelcast/client/protocol/ClientMessage.h:36:0,
                 from /tmp/hazelcast-cpp-client-4.0.1/hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.h:22,
                 from /tmp/hazelcast-cpp-client-4.0.1/hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.cpp:21:
/tmp/hazelcast-cpp-client-4.0.1/hazelcast/include/hazelcast/client/query/paging_predicate.h:63:13: warning: type attributes ignored after type is already defined [-Wattributes]
             };
             ^
gmake[2]: *** [CMakeFiles/hazelcast-cpp-client.dir/hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/hazelcast-cpp-client.dir/all] Error 2
gmake: *** [all] Error 2
```

#### Expected behaviour

build pass 
#### Actual behaviour
build error

#### Steps to reproduce the behaviour
mkdir build
cd build
cmake ..
cmake --build .

**Comment by yemreinci** [comment] 2021-04-28 09:41
Hello @whoareu, can you provide the version of the C++ compiler on your system? If you can, please also add the output of the configuration command (the first call to cmake, `cmake ..`).

**Comment by ihsandemir** [comment] 2021-05-05 02:13
@yemreinci I think it is reproducible using docker build `docker/hazelcast-fedora22-x86_64.dockerfile`. It seems to happen on earlier gcc versions. I observed this in nightly test build logs http://jenkins.hazelcast.com/view/C++/job/cpp-fedora22-64-SHARED-Debug/  when i change for example `enum struct HAZELCAST_API serialization_constants` with `enum HAZELCAST_API serialization_constants` the problem disappears. Seems like a warning about using the struct or class keyword in enum definitions.

e.g. errors:

```
06:52:49 /usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_VERSION=5 -DHAZELCAST_GIT_COMMIT_DATE="Fri Apr 30 18:34:35 2021 +0300" -DHAZELCAST_GIT_COMMIT_ID=763a61f -DHAZELCAST_VERSION=\"4.1.0\" -DHZ_BUILD_WITH_SSL -Dhazelcast_cpp_client_EXPORTS -I/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include -I/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/generated-sources/src -I/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/build/include -m64 -Wall -g -fPIC -std=gnu++11 -o CMakeFiles/hazelcast-cpp-client.dir/hazelcast/src/hazelcast/client/client_impl.cpp.o -c /home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/src/hazelcast/client/client_impl.cpp
06:52:51 In file included from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/address.h:20:0[m[K,
06:52:51                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/member.h:22[m[K,
06:52:51                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/entry_event.h:20[m[K,
06:52:51                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/proxy/IMapImpl.h:18[m[K,
06:52:51                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/imap.h:31[m[K,
06:52:51                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/map/NearCachedClientMapProxy.h:20[m[K,
06:52:51                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/impl/hazelcast_client_instance_impl.h:25[m[K,
06:52:51                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/hazelcast_client.h:20[m[K,
06:52:51                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/src/hazelcast/client/client_impl.cpp:41[m[K:
06:52:51 [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/serialization/serialization.h:93:17:[m[K [01;35m[Kwarning: [m[Ktype attributes ignored after type is already defined [-Wattributes]
06:52:51                  };
06:52:51 [01;32m[K                 ^[m[K
06:52:52 In file included from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/proxy/IMapImpl.h:19:0[m[K,
06:52:52                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/imap.h:31[m[K,
06:52:52                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/map/NearCachedClientMapProxy.h:20[m[K,
06:52:52                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/impl/hazelcast_client_instance_impl.h:25[m[K,
06:52:52                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/hazelcast_client.h:20[m[K,
06:52:52                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/src/hazelcast/client/client_impl.cpp:41[m[K:
06:52:52 [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/query/paging_predicate.h:63:13:[m[K [01;35m[Kwarning: [m[Ktype attributes ignored after type is already defined [-Wattributes]
06:52:52              };
06:52:52 [01;32m[K             ^[m[K
06:52:52 In file included from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/config/eviction_config.h:22:0[m[K,
06:52:52                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/config/near_cache_config.h:19[m[K,
06:52:52                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/client_config.h:30[m[K,
06:52:52                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/spi/impl/ClientClusterServiceImpl.h:26[m[K,
06:52:52                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/impl/EntryEventHandler.h:24[m[K,
06:52:52                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/imap.h:32[m[K,
06:52:52                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/map/NearCachedClientMapProxy.h:20[m[K,
06:52:52                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/impl/hazelcast_client_instance_impl.h:25[m[K,
06:52:52                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/hazelcast_client.h:20[m[K,
06:52:52                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/src/hazelcast/client/client_impl.cpp:41[m[K:
06:52:52 [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/config/eviction_strategy_type.h:41:13:[m[K [01;35m[Kwarning: [m[Ktype attributes ignored after type is already defined [-Wattributes]
06:52:52              };
06:52:52 [01;32m[K             ^[m[K
06:52:53 In file included from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/impl/ItemEventHandler.h:21:0[m[K,
06:52:53                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/proxy/IQueueImpl.h:22[m[K,
06:52:53                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/iqueue.h:19[m[K,
06:52:53                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/impl/hazelcast_client_instance_impl.h:32[m[K,
06:52:53                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/hazelcast_client.h:20[m[K,
06:52:53                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/src/hazelcast/client/client_impl.cpp:41[m[K:
06:52:53 [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/item_event.h:32:9:[m[K [01;35m[Kwarning: [m[Ktype attributes ignored after type is already defined [-Wattributes]
06:52:53          };
06:52:53 [01;32m[K         ^[m[K
06:53:12 [ 15%] [32mBuilding CXX object CMakeFiles/hazelcast-cpp-client.dir/hazelcast/src/hazelcast/client/cluster.cpp.o[0m
06:53:12 /usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_VERSION=5 -DHAZELCAST_GIT_COMMIT_DATE="Fri Apr 30 18:34:35 2021 +0300" -DHAZELCAST_GIT_COMMIT_ID=763a61f -DHAZELCAST_VERSION=\"4.1.0\" -DHZ_BUILD_WITH_SSL -Dhazelcast_cpp_client_EXPORTS -I/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include -I/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/generated-sources/src -I/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/build/include -m64 -Wall -g -fPIC -std=gnu++11 -o CMakeFiles/hazelcast-cpp-client.dir/hazelcast/src/hazelcast/client/cluster.cpp.o -c /home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/src/hazelcast/client/cluster.cpp
06:53:13 In file included from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/address.h:20:0[m[K,
06:53:13                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/member.h:22[m[K,
06:53:13                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/cluster.h:21[m[K,
06:53:13                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/src/hazelcast/client/cluster.cpp:36[m[K:
06:53:13 [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/serialization/serialization.h:93:17:[m[K [01;35m[Kwarning: [m[Ktype attributes ignored after type is already defined [-Wattributes]
06:53:13                  };
06:53:13 [01;32m[K                 ^[m[K
06:53:14 In file included from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/config/eviction_config.h:22:0[m[K,
06:53:14                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/config/near_cache_config.h:19[m[K,
06:53:14                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/client_config.h:30[m[K,
06:53:14                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/spi/impl/ClientClusterServiceImpl.h:26[m[K,
06:53:14                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/src/hazelcast/client/cluster.cpp:37[m[K:
06:53:14 [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/config/eviction_strategy_type.h:41:13:[m[K [01;35m[Kwarning: [m[Ktype attributes ignored after type is already defined [-Wattributes]
06:53:14              };
06:53:14 [01;32m[K             ^[m[K
06:53:16 [ 21%] [32mBuilding CXX object CMakeFiles/hazelcast-cpp-client.dir/hazelcast/src/hazelcast/client/config.cpp.o[0m
06:53:16 /usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_VERSION=5 -DHAZELCAST_GIT_COMMIT_DATE="Fri Apr 30 18:34:35 2021 +0300" -DHAZELCAST_GIT_COMMIT_ID=763a61f -DHAZELCAST_VERSION=\"4.1.0\" -DHZ_BUILD_WITH_SSL -Dhazelcast_cpp_client_EXPORTS -I/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include -I/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/generated-sources/src -I/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/build/include -m64 -Wall -g -fPIC -std=gnu++11 -o CMakeFiles/hazelcast-cpp-client.dir/hazelcast/src/hazelcast/client/config.cpp.o -c /home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/src/hazelcast/client/config.cpp
06:53:17 In file included from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/address.h:20:0[m[K,
06:53:17                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/client_config.h:24[m[K,
06:53:17                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/src/hazelcast/client/config.cpp:34[m[K:
06:53:17 [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/serialization/serialization.h:93:17:[m[K [01;35m[Kwarning: [m[Ktype attributes ignored after type is already defined [-Wattributes]
06:53:17                  };
06:53:17 [01;32m[K                 ^[m[K
06:53:17 In file included from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/config/eviction_config.h:22:0[m[K,
06:53:17                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/config/near_cache_config.h:19[m[K,
06:53:17                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/client_config.h:30[m[K,
06:53:17                  from [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/src/hazelcast/client/config.cpp:34[m[K:
06:53:17 [01m[K/home/jenkins/jenkins_slave/workspace/cpp-fedora22-64-SHARED-Debug/hazelcast/include/hazelcast/client/config/eviction_strategy_type.h:41:13:[m[K [01;35m[Kwarning: [m[Ktype attributes ignored after type is already defined [-Wattributes]
06:53:17              };
```

**Comment by ihsandemir** [comment] 2021-05-05 13:40
It was false warning above, the error was actually this line which is different from our nightly build warnings: 
```
/tmp/hazelcast-cpp-client-4.0.1/hazelcast/include/hazelcast/client/serialization/serialization.h:776:32: error: ambiguous template specialization ‘write_object<>’ for ‘void hazelcast::client::serialization::object_data_output::write_object(const char*)’
             void HAZELCAST_API object_data_output::write_object(const char *object);
```

We still need to know what is the compiler version this occurs and the cmake configurat'on command logs as @yemreinci requested above.

**Comment by ihsandemir** [comment] 2021-08-19 11:52
@whoareu did you see the above question regarding the compiler version?

**Comment by yemreinci** [comment] 2021-12-21 15:09
@whoareu, I am closing this as we couldn't reproduce this. 

Please reopen with your compiler version information if you are still experiencing this issue.

**Closed by yemreinci** 2021-12-21 15:09 UTC
Labels: Type: Defect, Source: Community, to-jira
