### ISSUE TITLE
LoadTest.testIntMapSmartClientServerRestart

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast-cpp-client#136] opened 2016-05-23 12:32 UTC
```
/appdisk/jenkins/jenkins/workspace/cpp-linux-nightly-64-STATIC-Release/hazelcast/test/src/faulttolerance/LoadTest.cpp:55
Expected: map->put(i, i) doesn't throw an exception.
  Actual: it throws.
```

https://hazelcast-l337.ci.cloudbees.com/view/C++/job/cpp-linux-nightly-64-STATIC-Release/109/testReport/junit/(root)/LoadTest/testIntMapSmartClientServerRestart/

**Comment by hasancelik** [comment] 2016-06-20 07:18
```
/home/jenkins/jenkins/workspace/cpp-linux/hazelcast/test/src/faulttolerance/LoadTest.cpp:61
Expected: val = map->get(i) doesn't throw an exception.
  Actual: it throws.
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/cpp-linux/539/testReport/junit/(root)/LoadTest/testIntMapSmartClientServerRestart/

**Comment by ihsandemir** [comment] 2017-11-10 07:42
This is duplicate of issue https://github.com/hazelcast/hazelcast-cpp-client/issues/227

**Closed** 2017-11-10 08:11 UTC
Labels: test-failure
